language: rust

cache: cargo

rust:
  # - stable
  # - beta
  - nightly

# matrix:
#   allow_failures:
#     - rust: nightly
#   fast_finish: true

env:
  - FEATURES="f32"
  - FEATURES="f64"
  - FEATURES="f32 serde1"
  - FEATURES="f64 serde1"

before_script:
  - rustup component add clippy

script:
  - cargo build --verbose --features="$FEATURES"
  - cargo clippy --verbose --features="$FEATURES"
  - cargo test --verbose --features="$FEATURES"

notifications:
  email:
    on_success: never
