language: rust

cache: cargo

rust:
#  - stable
#  - beta
  - nightly

#matrix:
#  allow_failures:
#    - rust: nightly
#  fast_finish: true

env:
  - FP_MODE=f32
  - FP_MODE=f64

script:
  - cargo build --verbose --features $FP_MODE
  - cargo test --verbose --features $FP_MODE

notifications:
  email:
    on_success: never
