[package]
name = "ava"
version = "0.0.3"
authors = ["Guilherme G. Ferrari <gg.ferrari@gmail.com>"]
description = "N-body experiments in Rust"
homepage = "https://crates.io/crates/ava"
documentation = "https://docs.rs/ava"
readme = "README.md"
license = "MIT"
repository = "https://github.com/ggf84/ava"

[dependencies]
